# Register at https://openweathermap.org to get your API key
api_key = "e01a53b3b673ada483ce28396296082a"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "4682380"

# Display settings
units = "imperial"
display_symbol = "°F"