#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/wickedlester/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

#== misc
picom --config ~/.config/picom/picom.conf --experimental-backends &
dunst &
xrdb -load ~/.Xresources &

#== polybar
#/home/sandman/.config/polybar_openbox/run.sh &
#tint2 &

#== thunar starting in daemon mode
#thunar --daemon &

#=== network manager applet
nm-applet &

#=== battery icon
cbatticon &

#== system tray
#sleep 1; trayer --edge bottom --align left --widthtype request --SetDockType false --expand true &

#== bluetooth
blueman-applet &

#== Set background image
(sleep 1; nitrogen --restore) &
#~/.fehbg &

#== on laptops without seperate numeric keyboard put hashtag in front
numlockx &

#== GNOME PolicyKit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#== Volume control for systray
#(sleep 2; volumeicon) &
#(sleep 2; pasystray --always-notify) &

#== Turn off/on System Beep
#xset b off

#== set dpms
#xset dpms 0 0 600 &

#== Enable power management
#xfce4-power-manager &
#caffeine &


#== Clipboard Manager
#(sleep 3; clipit) &

#== hot corners with cornora-git
cornora -tr "skippy-xd" -bl "sleep 1; xset dpms force off" -v -iof &
#cornora -tr "skippy-xd" -bl "sleep 1; xset dpms force off"
#== XFCE4 Settings
#xfsettingsd &
#xfsettingsd --sm-client-disable --disable-wm-check &
#=== gtk settings
xsettingsd &

#== lock screen
#xautolock -time 10 -locker blurlock4.sh -corners '+00-'
xautolock -time 10 -locker i3lock-fancy -corners '+00-' &

## Enable Super Keys For Menu
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &


# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/wickedlester/.fluxbox/log"
